name: Build

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: msbuild "Simple Icon File Maker.sln" /t:Restore /p:Configuration=Release /p:Platform=x64

    - name: Build solution
      run: msbuild "Simple Icon File Maker.sln" /p:Configuration=Release /p:Platform=x64
